#
# PLEASE RELOAD OR RESTART SERVER AFTER A CHANGE IN THIS FILE.
# More information on plugin page : https://dev.bukkit.org/projects/mobsmanager
# Any trouble to use this file ? Ask help on Discord : https://discordapp.com/invite/jCsvJxS
#
auto-update: true
world-guard-detection: false


