name: MobsManager
main: me.crylonz.MobsManager
version: "5.5.0"
author: Crylonz
softdepend: [Multiverse-Core, WorldGuard]
description: MobsManager
api-version: "1.13"
commands:
  mobsmanager:
    description: List of commands
    aliases: mm
    usage: use /mobsmanager help
permissions:
  mobsmanager.manageEntity:
    description: Allows you to disable or enable entity on the server
    default: op
  mobsmanager.reload:
    description: Allows you to reload the plugin
    default: op
  mobsmanager.help:
    description: Display help
    default: op
  mobsmanager.info:
    description: Allows you to see spawn info of a world
    default: op